setup: 'eanqg_squad_split_v2'

#########################################################################################################
# ---------------------------------------- DATA CONFIGURATIONS ---------------------------------------- #
#########################################################################################################

cached_train_path: 'data/squad_split_v2/train.pt'
cached_dev_path: 'data/squad_split_v2/dev.pt'
cached_test_path: 'data/squad_split_v2/test.pt'
cached_vocabularies_path: 'data/squad_split_v2/vocab.pt'

vocab_size: 45000

min_word_frequency: 1

max_source_length: 200
max_target_length: 50


##########################################################################################################
# ---------------------------------------- MODEL CONFIGURATIONS ---------------------------------------- #
##########################################################################################################

model:
    embedding_size: 300

    feature_num: 0
    feature_tag_embedding_size: 3
    answer_tag_embedding_size: 16

    hidden_size: 512
    num_layers: 2
    dropout: 0.3
    layer_norm_eps: 0.000000000001
    hidden_dropout_prob: 0.1

    use_pointer: False

# Initialization
param_init: 0.1
param_init_glorot: True


#########################################################################################################
# -------------------------------------- TRAINING CONFIGURATIONS -------------------------------------- #
#########################################################################################################

cached_model_dir: checkpoints

num_train_epochs: 10
#num_train_steps: 25000
#num_valid_steps: 500

batch_size: 64

optimizer_name: adam
sgd_learning_rate: 0.1
adam_learning_rate: 0.0003

max_grad_norm: 5.

max_to_keep: 20


#########################################################################################################
# ------------------------------------- INFERENCE CONFIGURATIONS ------------------------------------- #
#########################################################################################################

beam_size: 15
min_decode_step: 8
max_decode_step: 30

output: generated_question.txt