setup: 'eanqg_newsqa'

#########################################################################################################
# ---------------------------------------- DATA CONFIGURATIONS ---------------------------------------- #
#########################################################################################################

cached_train_path: 'data/newsqa/train.pt'
cached_dev_path: 'data/newsqa/dev.pt'
cached_test_path: 'data/newsqa/test.pt'
cached_vocabularies_path: 'data/newsqa/vocab.pt'

vocab_size: 45000

min_word_frequency: 1

max_source_length: 200
max_target_length: 50


##########################################################################################################
# ---------------------------------------- MODEL CONFIGURATIONS ---------------------------------------- #
##########################################################################################################

model:
    embedding_size: 300

    feature_num: 2
    feature_tag_embedding_size: 16
    answer_tag_embedding_size: 16

    hidden_size: 300
    num_layers: 2
    dropout: 0.3
    layer_norm_eps: 0.000000000001
    hidden_dropout_prob: 0.1

    use_pointer: True

# Initialization
param_init: 0.1
param_init_glorot: True


#########################################################################################################
# -------------------------------------- TRAINING CONFIGURATIONS -------------------------------------- #
#########################################################################################################

cached_model_dir: checkpoints

num_train_epochs: 20
#num_train_steps: 25000
#num_valid_steps: 500

batch_size: 64

optimizer_name: sgd
sgd_learning_rate: 0.1
adam_learning_rate: 0.001

max_grad_norm: 5.

max_to_keep: 20


#########################################################################################################
# ------------------------------------- INFERENCE CONFIGURATIONS ------------------------------------- #
#########################################################################################################

beam_size: 10
min_decode_step: 3
max_decode_step: 40

output: generated_question.txt